//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESMAN_MASTER
    {
        public string SALESMANNO { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public Nullable<decimal> PINCODE { get; set; }
        public string STATE { get; set; }
        public decimal SALAMT { get; set; }
        public decimal TGTTOGET { get; set; }
        public decimal YTDSALES { get; set; }
        public string REMARKS { get; set; }
    }
}
